# Generated by Django 5.1.5 on 2025-01-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/users/avatars/",
                verbose_name="аватар",
            ),
        ),
    ]
