# Generated by Django 5.1.5 on 2025-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.FloatField(
                blank=True, null=True, verbose_name="рейтинг продавца"
            ),
        ),
    ]
