# Generated by Django 5.1.5 on 2025-01-27 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterConfirmToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="токен регистрации",
                    ),
                ),
            ],
        ),
    ]
