# Generated by Django 5.1.5 on 2025-02-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/media/users/avatars/wo-avatar.png",
                null=True,
                upload_to="users/avatars/",
                verbose_name="аватар",
            ),
        ),
    ]
