# Generated by Django 5.1.5 on 2025-01-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerconfirmtoken",
            name="token",
            field=models.CharField(max_length=40),
        ),
    ]
