# Generated by Django 5.1.5 on 2025-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notif_email",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="признак уведомления по почте",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notif_tg",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="признак уведомления по tg",
            ),
        ),
    ]
