# Generated by Django 5.1.5 on 2025-02-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_notif_email_user_notif_tg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notif_email",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="признак уведомления по почте"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notif_tg",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="признак уведомления по tg"
            ),
        ),
    ]
