# Generated by Django 5.1.5 on 2025-02-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_notif_email_alter_user_notif_tg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notif_email",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Уведомления по почте"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notif_tg",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Уведомления в Telegram"
            ),
        ),
    ]
