# Generated by Django 5.1.5 on 2025-01-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/avatars/", verbose_name="аватар"
            ),
        ),
    ]
