# Generated by Django 5.1.5 on 2025-02-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0025_alter_filter_filter_word"),
        ("users", "0009_alter_user_notif_email_alter_user_notif_tg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="filter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.filter",
                verbose_name="фильтр уведомлений",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="store",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.store",
                verbose_name="магазин пользователя",
            ),
        ),
    ]
