# Generated by Django 5.1.5 on 2025-01-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="признак активности"
                    ),
                ),
            ],
            options={
                "verbose_name": "чат",
                "verbose_name_plural": "чаты",
            },
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter_word",
                    models.CharField(max_length=100, verbose_name="фильтрующее слово"),
                ),
            ],
            options={
                "verbose_name": "фильтр уведомления",
                "verbose_name_plural": "фильтр уведомления",
            },
        ),
        migrations.CreateModel(
            name="NotifSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tg_notif",
                    models.BooleanField(
                        default=False,
                        verbose_name="признак отправки уведомления на telegram",
                    ),
                ),
                (
                    "email_notif",
                    models.BooleanField(
                        default=False,
                        verbose_name="признак отправки уведомления на email",
                    ),
                ),
            ],
            options={
                "verbose_name": "настройка уведомлений",
                "verbose_name_plural": "настройки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_text", models.TextField(verbose_name="текст заявки")),
                (
                    "request_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/request_photos/",
                        verbose_name="фотографии заявки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="признак активной заявки"
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField(verbose_name="оценка")),
                ("review_text", models.TextField(verbose_name="текст отзыва")),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=30, verbose_name="город магазина"),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="адрес магазина"),
                ),
            ],
            options={
                "verbose_name": "магазин",
                "verbose_name_plural": "магазины",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_text", models.TextField(verbose_name="текст сообщения")),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/photos/message_photos/",
                        verbose_name="фото сообщения",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat",
                        to="mainapp.chat",
                        verbose_name="чат к которому привязано сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
