# Generated by Django 5.1.5 on 2025-01-29 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_from",
                to=settings.AUTH_USER_MODEL,
                verbose_name="от",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кому",
            ),
        ),
        migrations.AddField(
            model_name="notifsetting",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notif_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец настройки",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель заявки",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat",
                to="mainapp.request",
                verbose_name="заявка",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writed_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ревьювер",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="продавец",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец магазина",
            ),
        ),
    ]
