# Generated by Django 5.1.5 on 2025-01-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="время создания заявки"
            ),
        ),
    ]
