# Generated by Django 5.1.5 on 2025-01-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="city_not_matter",
            field=models.BooleanField(
                blank=True,
                help_text="город в поле выше учитываться не будет",
                verbose_name="Город не важен",
            ),
        ),
    ]
