# Generated by Django 5.1.5 on 2025-01-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_request_city_not_matter"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="model",
            field=models.CharField(
                default="", max_length=30, verbose_name="модель авто"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="car",
            field=models.CharField(max_length=30, verbose_name="марка"),
        ),
    ]
