# Generated by Django 5.1.5 on 2025-01-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_request_model_alter_request_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="model",
            field=models.CharField(default="", max_length=30, verbose_name="модель"),
        ),
    ]
