# Generated by Django 5.1.5 on 2025-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_alter_request_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="укажите город, если хотите уменьшить количество поступаемых предложений",
                max_length=30,
                null=True,
                verbose_name="город",
            ),
        ),
    ]
