# Generated by Django 5.1.5 on 2025-01-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_request_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="год",
            ),
        ),
    ]
