# Generated by Django 5.1.5 on 2025-01-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_request_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, default="", null=True, verbose_name="год"
            ),
        ),
    ]
