# Generated by Django 5.1.5 on 2025-01-31 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_request_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="инициатор чата",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="признак активности"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="mainapp.request",
                verbose_name="заявка",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, default=None, null=True, verbose_name="год"
            ),
        ),
    ]
