# Generated by Django 5.1.5 on 2025-02-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_chat_created_by_alter_chat_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="признак активности"),
        ),
    ]
