# Generated by Django 5.1.5 on 2025-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_alter_chat_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/photos/message_photos/",
                verbose_name="фото сообщения",
            ),
        ),
    ]
