# Generated by Django 5.1.5 on 2025-02-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_alter_message_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat",
                to="mainapp.chat",
                verbose_name="чат к которому привязано сообщение",
            ),
        ),
    ]
