# Generated by Django 5.1.5 on 2025-02-02 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_alter_message_chat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_from",
                to=settings.AUTH_USER_MODEL,
                verbose_name="от",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кому",
            ),
        ),
    ]
