# Generated by Django 5.1.5 on 2025-02-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_alter_message_from_user_alter_message_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sended_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="время отправки"
            ),
        ),
    ]
