# Generated by Django 5.1.5 on 2025-02-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_message_sended_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="readed",
            field=models.BooleanField(
                default=False, verbose_name="признак просмотрености"
            ),
        ),
    ]
