# Generated by Django 5.1.5 on 2025-02-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0015_message_readed"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="дата последнего обновления"
            ),
        ),
    ]
