# Generated by Django 5.1.5 on 2025-02-06 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0016_chat_last_updated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="название магазина"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store",
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец магазина",
            ),
        ),
    ]
