# Generated by Django 5.1.5 on 2025-02-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0020_alter_store_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="owner",
        ),
    ]
