# Generated by Django 5.1.5 on 2025-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0021_remove_store_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="/request_photos/wo-image.bmp",
                null=True,
                upload_to="request_photos/",
                verbose_name="фотографии заявки",
            ),
        ),
        migrations.DeleteModel(
            name="NotifSetting",
        ),
    ]
