# Generated by Django 5.1.5 on 2025-02-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0022_alter_request_photo_delete_notifsetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="filter_word",
            field=models.CharField(max_length=255, verbose_name="фильтрующие слова"),
        ),
    ]
