# Generated by Django 5.1.5 on 2025-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0025_alter_filter_filter_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="filter_word",
            field=models.TextField(
                blank=True, null=True, verbose_name="фильтрующие слова"
            ),
        ),
    ]
