# Generated by Django 5.1.5 on 2025-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0026_alter_filter_filter_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="признак активной заявки"
            ),
        ),
    ]
